### ISSUE TITLE
リンクテキストの下線切り替えオプション追加

### ISSUE THREAD

**Issue by neocryses** [ritaworks/s3-template#33]
アンカータグ下線の有無を \_settings.scss上で切り替えられるようにしていただきたいです。

その際に、下線有りであればホバー時には下線無し
下線無しであればホバー時には下線有りになるようにお願いいたします。

**Comment by tanpopo1225** [comment]
デフォルトと逆の設定(デフォルトが下線ありなら下線無しでホバー時に下線をつける)を持ったクラスも用意していただけると助かります。

**Comment by tajimakento** [comment]
以下のようにmixinで作っておいて_settings.scssで指定するのはどうでしょうか？
記述あっているかわかりませんが...

```
mixin text-link($style){
  //$styleがdefault-lineだった時　hover時に下線が消える
  @else if $style == default-line{
    text-decoration: underline;
    &:hover{
      text-decoration: none;
    }
  }
  //$styleがhover-lineだった時　hover時に下線が付く
  @else if $style == hover-line{
    text-decoration: none;
    &:hover{
      text-decoration: underline;
    }
  }
}

//_base.scss
a {
  @include text-link($base-text-decoration);
  color: $base-link-color;
}

//_settings.scss
$base-text-decoration: default-line or hover-line);
```

**Comment by neocryses** [comment]
@tajimakento 
ご確認、ご対応いただきありがとうございます。

上記の例ですと高橋さんより頂いていた
> デフォルトと逆の設定(デフォルトが下線ありなら下線無しでホバー時に下線をつける)を持ったクラスも用意していただけると助かります。

が入っていないと思います。
以下のコードでカバー出来ると思いますが、いかがでしょうか？

_settings.scss内に記述
```scss
$link-underline: true !default;
```

_utility.scss内に記述
```scss
@mixin link() {
  @if $link-underline {
    text-decoration: none;
    &:hover {
      text-decoration: underline;
    }
  }
  @else {
    text-decoration: underline;
    &:hover {
      text-decoration: none;
    }
  }
}
```

_class.scss内に記述
```scss
.link {
  @include link;
}
```

_base.scss内に記述
```scss
@if ($link-underline) {
  $link-underline: false;
  @include link;
} else {
  @include link;
}
```
